/****************************************************************************
*
* (C) 2003 by BECK IPC GmbH
*
*  BECK IPC GmbH
*  Garbenheimerstr. 36-38
*  D-35578 Wetzlar
*
*  Phone : (49)-6441-905-0
*  Fax   : (49)-6441-905-245
*
* ---------------------------------------------------------------------------
*  Module        : CLIB.H
*  Function      : RTOS C library include file
* ---------------------------------------------------------------------------

   $Header: CLIB.H, 3, 22.01.2004 17:42:14, Andre Pribil$

*****************************************************************************/


#ifndef _CLIB_H_
  #define _CLIB_H_

  #include "BIOS_API.H"
  #include "CGIAPI.H"
  #include "FOSSIL.H"
  #include "HWAPI.H"
  #include "I2C_API.H"
  #include "SPIAPI.H"
  #include "PKTDRV.H"
  #include "RTOS.H"
  #include "RTXERR.H"
  #include "TCPIP.H"
  #include "HELPER.H"

#endif // _CLIB_H_
